version: '3'

services:

  web:
    image: "app-web:${WEB_VERSION:-1.0}"
    container_name: app-server
    depends_on:
      - mariadb
      - mongodb
    links:
      - mariadb:mariadb
      - mongodb:mongodb
    ports:
      - "${WEB_PORT:-8000}:80"
    # In production use .env files or ${ENV_VAR} syntax
    environment:
      MYSQL_HOST: mariadb
      MYSQL_ROOT: password
      MYSQL_DATABASE: mysite
      MYSQL_USER: mysite
      MYSQL_PASSWORD: mysite
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: mysite
      MONGODB_USER: root
      MONGODB_PASSWORD: password

  worker:
    image: "app-worker:${WORKER_VERSION:-1.0}"
    container_name: app-worker
    depends_on:
      - mariadb
      - mongodb
    links:
      - mariadb:mariadb
      - mongodb:mongodb

  mariadb:
    image: mariadb:10.4
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysite
      MYSQL_USER: mysite
      MYSQL_PASSWORD: mysite
    volumes:
      - ./data/mariadb/db:/var/lib/mysql
      # Place init .sql file(s) at path below
      - ./data/mariadb/init:/docker-entrypoint-initdb.d
      - /tmp:/tmp
    expose:
      - "3306"
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:4-xenial
    container_name: app-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mysite
    volumes:
      - ./data/mongodb/db:/data/db
      # Place init .js file(s) at path below
      - ./data/mongodb/init:/docker-entrypoint-initdb.d
      - /tmp:/tmp
    expose:
      - "27017"
    ports:
      - "27017:27017"
