version: '3'

services:

  mariadb:
    image: mariadb:10.4
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysite
      MYSQL_USER: mysite
      MYSQL_PASSWORD: mysite
    volumes:
      - ./data/mariadb/db:/var/lib/mysql
      # Place init .sql file(s) at path below
      - ./data/mariadb/init:/docker-entrypoint-initdb.d
      - /tmp:/tmp
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - backend

  postgres:
    image: postgres:15-alpine
    container_name: app-postgres
    environment:
      POSTGRES_DB: mysite
      POSTGRES_USER: mysite
      POSTGRES_PASSWORD: mysite
    volumes:
      - ./data/postgres/db:/var/lib/postgresql/data
      # Place init .sql file(s) at path below
      - ./data/postgres/init:/docker-entrypoint-initdb.d
      - /tmp:/tmp
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
