version: '3'

services:

  web:
    image: "app-web:${WEB_VERSION:-1.0}"
    container_name: app-server
    networks:
      - backend
    depends_on:
      - mariadb
      - postgres
    links:
      - mariadb:mariadb
      - postgres:postgres
    ports:
      - "${WEB_PORT:-8000}:80"
    # In production use .env files or ${ENV_VAR} syntax
    environment:
      MYSQL_HOST: mariadb
      MYSQL_ROOT: password
      MYSQL_DATABASE: mysite
      MYSQL_USER: mysite
      MYSQL_PASSWORD: mysite
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: mysite
      POSTGRES_USER: mysite
      POSTGRES_PASSWORD: mysite

  worker:
    image: "app-worker:${WORKER_VERSION:-1.0}"
    container_name: app-worker
    networks:
      - backend
    depends_on:
      - mariadb
      - postgres
    links:
      - mariadb:mariadb
      - postgres:postgres

networks:
  backend:
    driver: bridge
