version: '3'

services:

  web:
    build:
      context: ./src/
      # must be relative to context directory
      dockerfile: ../build/Dockerfile.web
    image: app-web:1.0
    container_name: app-server
    networks:
      - backend
    depends_on:
      - mariadb
      - mongodb
    links:
      - mariadb:mariadb
      - mongodb:mongodb
    ports:
      - "${WEB_PORT:-8000}:80"
    # In production use .env files or ${ENV_VAR} syntax
    environment:
      MYSQL_HOST: mariadb
      MYSQL_ROOT: password
      MYSQL_DATABASE: mysite
      MYSQL_USER: mysite
      MYSQL_PASSWORD: mysite
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: mysite
      MONGODB_USER: root
      MONGODB_PASSWORD: password

  worker:
    build:
      context: ./src/
      # must be relative to context directory
      dockerfile: ../build/Dockerfile.worker
    image: app-worker:1.0
    container_name: app-worker
    networks:
      - backend
    depends_on:
      - mariadb
      - mongodb
    links:
      - mariadb:mariadb
      - mongodb:mongodb

networks:
  backend:
    driver: bridge
