#!/bin/bash

path=$0
if [[ -L $0 ]]; then
    path=$(readlink $0)
fi
DIR="$(cd "$(dirname "$path")" && pwd)"

if [ $# == 0 ]; then
    echo "Usage: ./prod <start|stop|logs>"
    exit 1
fi

if [ $1 == "start" ]; then
    echo "Starting..."
    WEB_VERSION=$(if [ -f web.version ]; then cat $DIR/build/web.version; fi) \
        WORKER_VERSION=$(if [ -f worker.version ]; then cat $DIR/build/worker.version; fi) \
        docker-compose -f $DIR/docker-compose.prod.yml up --force-recreate -d $2
    exit $?
fi

if [ $1 == "stop" ]; then
    echo "Stopping..."
    if [ $2 ]; then
        docker-compose -f $DIR/docker-compose.prod.yml stop $2
    else
        docker-compose -f $DIR/docker-compose.prod.yml down
    fi
    exit $?
fi

if [ $1 == "logs" ]; then
    echo "Reading logs..."
    docker-compose logs -f $2
fi

if [ $1 == "ps" ]; then
    docker-compose -f $DIR/docker-compose.prod.yml ps
fi
