version: '3'

services:

  web:
    build:
      context: ./web/
    image: php-server:8.2-alpine
    container_name: php-server
    ports:
      - "8080:80"

  worker:
    build:
      context: ./worker/
    image: php-worker:8.2-alpine
    container_name: php-worker
